// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Autentica un usuario y devuelve un JWT (válido por 24h).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credenciales",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Credenciales inválidas",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crea una cuenta nueva (rol: buyer o seller).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Registrar usuario",
                "parameters": [
                    {
                        "description": "Datos de registro",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Body inválido o password débil",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email ya registrado",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Verifica que el server responde.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/profile/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Devuelve el perfil de preferencias del usuario autenticado. Si aún no fue configurado, devuelve un perfil vacío.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Mi perfil",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ProfileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Configura tipo de vehículo y rango de presupuesto.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profile"
                ],
                "summary": "Actualizar preferencias del comprador",
                "parameters": [
                    {
                        "description": "Preferencias",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ProfileResponse"
                        }
                    },
                    "400": {
                        "description": "Presupuesto inválido",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.UserResponse"
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.ProfileResponse": {
            "type": "object",
            "properties": {
                "budget_max": {
                    "type": "integer"
                },
                "budget_min": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 6
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "buyer",
                        "seller"
                    ]
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "budget_max": {
                    "type": "integer"
                },
                "budget_min": {
                    "type": "integer"
                },
                "vehicle_type": {
                    "type": "string"
                }
            }
        },
        "github_com_BenjaminAliagaMardones_automatch_internal_handler_dto.UserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Pegar el token devuelto por /auth/login con el prefijo \"Bearer \". Ejemplo: \"Bearer eyJhbGciOi...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "AutoMatch API",
	Description:      "Backend de AutoMatch — primera entrega (Auth + Perfil).\nPlataforma de matchmaking para vehículos usados (proyecto UCT).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
