sonar.projectKey=automatch-client
sonar.projectName=AutoMatch Frontend
sonar.projectVersion=1.0

sonar.host.url=https://sonarqube.inf.uct.cl/

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=src/main.jsx,src/App.jsx,src/test/**,node_modules/**,dist/**,src/App.css
sonar.coverage.exclusions=\
  src/main.jsx,\
  src/App.jsx,\
  src/test/**,\
  src/components/**,\
  src/hooks/**,\
  src/services/apiClient.js,\
  src/features/auth/**,\
  src/features/feed/components/**,\
  src/features/feed/containers/**,\
  src/features/feed/hooks/useSellerListings.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
